export const GET_CATEGORYS_LOAD = "GET_CATEGORYS_LOAD";
export const GET_CATEGORYS_SUCCESS = "GET_CATEGORYS_SUCCESS";
export const GET_CATEGORYS_FAIL = "GET_CATEGORYS_FAIL";

export const DELETE_CATEGORY = "DELETE_CATEGORY";



export const GET_CATEGORY = "GET_CATEGORY";



export const POST_CATEGORY = "POST_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";